function init(self)
	self.counter = 0
	self.show_demo_window = false
end

function update(self, dt)
	if self.show_demo_window then
		imgui.demo()
	end

	do
		imgui.window_begin("Hello, world!")
		imgui.text("This is some useful text.")
		self.show_demo_window = imgui.checkbox("Demo window", self.show_demo_window)
		if imgui.button("Button") then
			self.counter = self.counter + 1
		end
		imgui.same_line()
		imgui.text(("counter = %d"):format(self.counter))
		imgui.window_end();
	end
end